name: LSIF

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
      - name: install indexer
        run: dart pub global activate -sgit https://github.com/Workiva/lsif_indexer
      - run: mkdir lsif_index
      - name: Run indexer
        run: dart pub global run lsif_indexer -o lsif_index/index.lsif
      - name: Publish LSIF
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: lsif-index
          FOLDER: lsif_index
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
